# Patching & Tracking SDK Makefile
# Copyright 2004 GameSpy Industries

TARGET=pt
THREADS=yes
DEBUG=no
CFLAGS=

SRC = \
	../pttestc.c\
	../../../md5c.c\
	../../../darray.c\
	../../../hashtable.c\
	../../../common/gsAvailable.c\
	../../../common/gsCrypt.c\
	../../../common/gsDebug.c\
	../../../common/gsLargeInt.c\
	../../../common/gsStringUtil.c\
	../../../common/gsPlatform.c\
	../../../common/gsPlatformSocket.c\
	../../../common/gsPlatformThread.c\
	../../../common/gsPlatformUtil.c\
	../../../common/gsDebug.c\
	../../../common/gsXML.c\
	../../../common/gsRC4.c\
	../../../common/gsSHA1.c\
	../../../common/gsSSL.c\
	../../../common/gsMemory.c\
	../../../common/linux/LinuxCommon.c\
	../../ptMain.c\
	../../../ghttp/ghttpBuffer.c\
	../../../ghttp/ghttpCallbacks.c\
	../../../ghttp/ghttpCommon.c\
	../../../ghttp/ghttpConnection.c\
	../../../ghttp/ghttpEncryption.c\
	../../../ghttp/ghttpMain.c\
	../../../ghttp/ghttpPost.c\
	../../../ghttp/ghttpProcess.c\

include ../../../common/linux/Makefile.common
